export type ProductPresentation = { intro: string; character: string; intensity?: number };

// Editorial tasting copy. Ingredients and prices remain in menu.json.
export const productPresentation: Record<string, ProductPresentation> = {
  '1': { intro: 'Kısa fincanda kahvenin doğrudan karakteri.', character: 'Kısa · tok', intensity: 4 },
  '2': { intro: 'Espressonun daha uzun ve sakin içimi.', character: 'Uzun · sade', intensity: 2 },
  '3': { intro: 'Yavaş içilen geleneksel fincan.', character: 'Geleneksel · yoğun', intensity: 4 },
  '4': { intro: 'Sütle yumuşayan dengeli kahve.', character: 'Yumuşak · sütlü', intensity: 2 },
  '5': { intro: 'Latteye tahinin sıcak dokunuşu.', character: 'Kremamsı · susamsı', intensity: 2 },
  '6': { intro: 'Küçük ölçekte daha belirgin bir kahve-süt dengesi.', character: 'Kısa · dengeli', intensity: 3 },
  '7': { intro: 'İnce süt dokusu, net bir kahve bitişi.', character: 'Düz · kadifemsi', intensity: 3 },
  '8': { intro: 'Espresso ve az sütle kurulan sade denge.', character: 'Kısa · dengeli', intensity: 3 },
  '9': { intro: 'Köpüğün yumuşattığı klasik kahve.', character: 'Hafif · köpüklü', intensity: 2 },
  '10': { intro: 'Kahve ile çikolatanın tanıdık birlikteliği.', character: 'Çikolatalı · tok', intensity: 2 },
  '11': { intro: 'Mocha çizgisinin daha yumuşak yorumu.', character: 'Tatlı · kremamsı', intensity: 2 },
  '12': { intro: 'Günün her saatine eşlik eden yalın fincan.', character: 'Sade · uzun', intensity: 2 },
  '13': { intro: 'Espressonun üzerinde küçük bir süt dokunuşu.', character: 'Kısa · belirgin', intensity: 4 },
  '14': { intro: 'Mocha ailesinin kontrastlı Zoi yorumu.', character: 'Katmanlı · çikolatalı', intensity: 2 },
  '15': { intro: 'Yumuşak ve sıcak bir kahve molası.', character: 'Yumuşak · aromatik', intensity: 2 },
  '16': { intro: 'Klasik mocha çizgisinden daha cesur bir yorum.', character: 'Belirgin · tatlı', intensity: 2 },
  '17': { intro: 'Ahududu notasıyla değişen mocha dengesi.', character: 'Meyvemsi · çikolatalı', intensity: 2 },
  '18': { intro: 'Lattenin serin ve akışkan hali.', character: 'Soğuk · sütlü', intensity: 2 },
  '19': { intro: 'Buzla açılan, sade ve uzun kahve.', character: 'Soğuk · net', intensity: 2 },
  '20': { intro: 'Mocha lezzetini serin bir molaya taşıyan seçim.', character: 'Soğuk · çikolatalı', intensity: 2 },
  '21': { intro: 'Filtre kahvenin buzla ferahlayan hali.', character: 'Soğuk · sade', intensity: 2 },
  '22': { intro: 'Katmanlı mocha karakteri, buzla birlikte.', character: 'Soğuk · katmanlı', intensity: 2 },
  '23': { intro: 'White mocha çizgisinin serin yorumu.', character: 'Soğuk · kremamsı', intensity: 2 },
  '24': { intro: 'Flat white dengesini daha ferah bir içimde buluşturur.', character: 'Soğuk · dengeli', intensity: 3 },
  '25': { intro: 'Dondurma ile espressonun kısa buluşması.', character: 'Tatlı · yoğun', intensity: 3 },
  '26': { intro: 'Matchanın bitkisel karakteri, sütle yumuşar.', character: 'Bitkisel · yumuşak', intensity: 2 },
  '27': { intro: 'Matcha ve sütün buzla serinleyen dengesi.', character: 'Serin · bitkisel', intensity: 2 },
  '45': { intro: 'Paylaşması kolay, çıtır bir eşlikçi.', character: 'Çıtır · tuzlu' },
  '46': { intro: 'Çıtır tavuk ve patatesin bir araya geldiği tabak.', character: 'Çıtır · doyurucu' },
  '49': { intro: 'Karamelize yüzeyiyle sade bir tatlı molası.', character: 'Kremamsı · yoğun' },
  '50': { intro: 'Kat kat, kahveye eşlik eden yumuşak bir klasik.', character: 'Hafif · katmanlı' },
  '52': { intro: 'Çikolata soslu küçük bir tatlı molası.', character: 'Çikolatalı · yumuşak' },
  '54': { intro: 'Çileğin serin ve canlı hali.', character: 'Meyvemsi · buzlu' },
  '55': { intro: 'Çarkıfeleğin tropik ferahlığı.', character: 'Tropik · buzlu' },
  '56': { intro: 'Mangonun yazlık, serin yorumu.', character: 'Tropik · buzlu' },
  '60': { intro: 'Günün temposuna kısa bir çay molası.', character: 'Sıcak · sade' },
};

export const pairingByCategory: Record<string, string[]> = {
  'Espresso Bar': ['49', '50', '51', '52'],
  'Zoi Bar': ['49', '50', '51', '52'],
  'Ice Bar': ['49', '51', '53'],
  'Matcha': ['49', '53'],
  'Kokteyl': ['36', '37', '39', '40'],
  'Gurme Sandviç': ['34', '18', '70'],
  'Tostlar': ['34', '70', '60'],
  'Başlangıçlar': ['34', '70', '61'],
  'Makarna Mantı': ['34', '70'],
  'Tatlılar': ['1', '4', '8', '18'],
  'Dondurma': ['1', '8'],
  'Frozen & Milkshake': ['49', '51'],
  'Tea Pot': ['49', '50'],
  'Soğuk İçecekler': ['36', '41', '44'],
  'Lüks Çerez': ['60', '61'],
};
